services:

  actus-riskserver-ce: # specify service name as specified in application.properties of actus-service
    image: fnparr/actus-riskserver-ce:mdb27017   #currently local image (needs to be built first) will be replaced with a published imaged
    ports:
      - "8082:8082" # Change to the appropriate port if needed

  actus-server-rf20:
    image: fnparr/actus-server-rf20:mdb27017 #currently local image (needs to be built first) will be replaced with a published imaged
    ports:
      - "8083:8083"  # Change to the appropriate port if needed
