version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db
    networks:
      - actus-network

  actus-riskserver-ce:
    image: mtoub/actus-riskserver-ce:mdb27018
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/actusdb
    depends_on:
      - mongodb
    networks:
      - actus-network

  actus-server-rf20:
    image: mtoub/actus-server-rf20:nodb
    ports:
      - "8083:8083"
    networks:
      - actus-network

volumes:
  mongo_data:

networks:
  actus-network:
    driver: bridge
